### ISSUE TITLE
License

### ISSUE THREAD

**Issue by federico-razzoli** [MarkLeith/dbahelper#7]
I have noticed that ps_helper has no copyright note or license. If the author is aware of the legal consequences, it's ok, this is not a complaint. However, most developers seems not to know that a missing license is equivalent to "all rights reserved" - which means that modifying the software or sending it to a friend is illegal.

I'd really appreciate to see a license.

**Comment by MarkLeith** [comment]
I am indeed aware of the consequences. 

FWIW, I had commented originally on ps_helper as being under the WTFPL. It still kind of is as far as I'm concerned. 

That being said, I've created a new "mysql-sys" branch now, forked from ps_helper last week, that instead creates a "sys" schema. This will be used by MySQL Workbench, and may find it's way in to mainline MySQL at some point in the future. That branch is licensed under the GPLv2 license, and copyright belongs to Oracle.

This already has improvements over dbahelper/ps_helper (which I'm unlikely to merge back, otherwise I would really have to consider changing ps_helper to GPLv2 as well, and I would like it to remain as a "playground" for new ideas as it has been so far).
